echo "env : $env" >> config
echo "implementation_name : $implementation_name" >> config
echo "ssh_ansible_user : $ssh_ansible_user" >> config
echo "ansible_private_key_path : $ansible_private_key_path" >> config
echo "application_host : $application_host" >> config
echo "app_address_space : $app_address_space" >> config
echo "dns_name : $dns_name" >> config
echo "proto : $proto" >> config
echo "database_host : $database_host" >> config
echo "database_password : $database_password" >> config
echo "keycloak_admin_password : $keycloak_admin_password" >> config
echo "sso_password : $sso_password" >> config
echo "trampoline_secret : $trampoline_secret" >> config
echo "backup_storage_key : $backup_storage_key" >> config
echo "badger_admin_password : $badger_admin_password" >> config
echo "badger_admin_email : $badger_admin_email" >> config
echo "ekstep_api_key : $ekstep_api_key" >> config
echo "sunbird_image_storage_url : $sunbird_image_storage_url" >> config
echo "sunbird_azure_storage_key : $sunbird_azure_storage_key" >> config
echo "sunbird_azure_storage_account : $sunbird_azure_storage_account" >> config

