echo "env : $env" >> configuration
echo "implementation_name : $implementation_name" >> configuration
echo "ssh_ansible_user : $ssh_ansible_user" >> configuration
echo "ansible_private_key_path : $ansible_private_key_path" >> configuration
echo "application_host : $application_host" >> configuration
echo "app_address_space : $app_address_space" >> configuration
echo "dns_name : $dns_name" >> configuration
echo "proto : $proto" >> configuration
echo "database_host : $database_host" >> configuration
echo "database_password : $database_password" >> configuration
echo "keycloak_admin_password : $keycloak_admin_password" >> configuration
echo "sso_password : $sso_password" >> configuration
echo "trampoline_secret : $trampoline_secret" >> configuration
echo "backup_storage_key : $backup_storage_key" >> configuration
echo "badger_admin_password : $badger_admin_password" >> configuration
echo "badger_admin_email : $badger_admin_email" >> configuration
echo "ekstep_api_key : $ekstep_api_key" >> configuration
echo "sunbird_image_storage_url : $sunbird_image_storage_url" >> configuration
echo "sunbird_azure_storage_key : $sunbird_azure_storage_key" >> configuration
echo "sunbird_azure_storage_account : $sunbird_azure_storage_account" >> configuration

