###### Release 1.14.0, 2.0.0 ########

env: dev
proto: https
domain_name: sunbird.centralindia.cloudapp.azure.com 
ekstep_domain_name: qa.ekstep.in

#bootstrap
ssh_public_key_deployer: "" # Optional
bootstrap_user: ops
bootstrap_key_path: /home/ops/deployer.pem

azure_public_container: learning
azure_account_name: 3node
environment_id:  1000000  # Should be a number of 8 digit like 1000000. This should be unique per environment
neo4j_zip: neo4j-community-3.3.9-unix.tar.gz      # neo4j enterprise version.zip present in the artifacts folder
neo4j_home: "{{learner_user_home}}/{{neo4j_dir}}/neo4j-community-3.3.9"   # Change this path to the version of neo4j you will be using
neo4j_enterprise: false

###########  Jenkinspipeline upload artifact ############
artifacts_container: 

## backup
backup_azure_storage_account_name:
backup_azure_storage_access_key: "{{lp_vault_azure_storage_secret}}"

swarm_manager_lb_ip: 10.1.4.4      # Enter the LB IP in case you are using a swarm manager load balancer OR Swarm manager's IP if not using a load balancer
